version: "3"
services: 
    web:
        build: 
            context: .
            dockerfile: Dockerfile.dev
        ports:
            - "3000:3000"
        volumes: 
            - /u01/app/node_modules
            - .:/u01/app
    test:
        build: 
            context: .
            dockerfile: Dockerfile.dev
        volumes: 
            - /u01/app/node_modules
            - .:/u01/app
        command: npm run test